// Generated by LiveScript 1.5.0
(function(){
  var gulp, gulpChanged, gulpUtil, gulpPrint, gulpLivescript, lspattern;
  gulp = require('gulp');
  gulpChanged = require('gulp-changed');
  gulpUtil = require('gulp-util');
  gulpPrint = require('gulp-print');
  gulpLivescript = require('gulp-livescript-async');
  lspattern = ['*.ls', 'www/*.ls', 'routes/*.ls', 'libs/*.ls'];
  gulp.task('livescript', function(){
    gulp.src(lspattern, {
      base: './'
    }).pipe(gulpChanged('.', {
      extension: '.js'
    })).pipe(gulpLivescript({
      bare: false
    })).on('error', gulpUtil.log).pipe(gulpPrint(function(it){
      return "livescript: " + it;
    })).pipe(gulp.dest('.'));
  });
  gulp.task('build', ['livescript']);
  gulp.task('watch', function(){
    return gulp.watch(lspattern, ['build']);
  });
  gulp.task('default', ['build', 'watch']);
}).call(this);
